// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2HLvGMnljJeaU44wxUgFr0w1lpTP_MGo',
    appId: '1:733217216941:web:e9f5ce26e89554bfe82924',
    messagingSenderId: '733217216941',
    projectId: 'adminapp-11b8c',
    authDomain: 'adminapp-11b8c.firebaseapp.com',
    storageBucket: 'adminapp-11b8c.appspot.com',
    measurementId: 'G-Z81RD30YX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8agV3SbH66I39hzUpTIdjqGzHD7Ovn5A',
    appId: '1:733217216941:android:2e0a9e1de3ede428e82924',
    messagingSenderId: '733217216941',
    projectId: 'adminapp-11b8c',
    storageBucket: 'adminapp-11b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpx08XoOunuX40h4-PWihT6geae0L88Q4',
    appId: '1:733217216941:ios:c96686e5ff0a1651e82924',
    messagingSenderId: '733217216941',
    projectId: 'adminapp-11b8c',
    storageBucket: 'adminapp-11b8c.appspot.com',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpx08XoOunuX40h4-PWihT6geae0L88Q4',
    appId: '1:733217216941:ios:c96686e5ff0a1651e82924',
    messagingSenderId: '733217216941',
    projectId: 'adminapp-11b8c',
    storageBucket: 'adminapp-11b8c.appspot.com',
    iosBundleId: 'com.example.adminapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2HLvGMnljJeaU44wxUgFr0w1lpTP_MGo',
    appId: '1:733217216941:web:4f3eb314ca2b1b35e82924',
    messagingSenderId: '733217216941',
    projectId: 'adminapp-11b8c',
    authDomain: 'adminapp-11b8c.firebaseapp.com',
    storageBucket: 'adminapp-11b8c.appspot.com',
    measurementId: 'G-HFHCXH491L',
  );
}
